modules/DoubleEntry/Routes/admin.php
<?php

Route::admin('double-entry', function () {
    Route::get('chart-of-accounts/{chart_of_account}/enable', 'ChartOfAccounts@enable')->name('chart-of-accounts.enable');
    Route::get('chart-of-accounts/{chart_of_account}/disable', 'ChartOfAccounts@disable')->name('chart-of-accounts.disable');
    Route::get('chart-of-accounts/{chart_of_account}/duplicate', 'ChartOfAccounts@duplicate')->name('chart-of-accounts.duplicate');
    Route::post('chart-of-accounts/import', 'ChartOfAccounts@import')->name('chart-of-accounts.import');
    Route::get('chart-of-accounts/export', 'ChartOfAccounts@export')->name('chart-of-accounts.export');
    Route::resource('chart-of-accounts', 'ChartOfAccounts');

    Route::get('journal-entry/{journal_entry}/duplicate', 'JournalEntry@duplicate')->name('journal-entry.duplicate');
    Route::post('journal-entry/import', 'JournalEntry@import')->name('journal-entry.import');
    Route::get('journal-entry/export', 'JournalEntry@export')->name('journal-entry.export');
    Route::resource('journal-entry', 'JournalEntry', ['middleware' => ['double-entry-money']]);

    Route::get('settings', 'Settings@edit')->name('settings.edit');
    Route::post('settings', 'Settings@update')->name('settings.update');
});

modules/DoubleEntry/Http/Controllers/JournalEntry.php
<?php

namespace Modules\DoubleEntry\Http\Controllers;

use App\Abstracts\Http\Controller;
use App\Http\Requests\Common\Import as ImportRequest;
use App\Models\Setting\Currency;
use App\Traits\DateTime;
use App\Traits\Documents;
use Modules\DoubleEntry\Exports\JournalEntry\Journals as Export;
use Modules\DoubleEntry\Http\Requests\Journal as Request;
use Modules\DoubleEntry\Imports\JournalEntry\Journals as Import;
use Modules\DoubleEntry\Jobs\Journal\CreateJournalEntry;
use Modules\DoubleEntry\Jobs\Journal\DeleteJournalEntry;
use Modules\DoubleEntry\Jobs\Journal\UpdateJournalEntry;
use Modules\DoubleEntry\Models\Account;
use Modules\DoubleEntry\Models\Journal;
use Modules\DoubleEntry\Models\Type;
use Modules\DoubleEntry\Traits\Journal as Traits;

class JournalEntry extends Controller
{
    use DateTime, Documents, Traits;

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $journals = Journal::collect(['paid_at' => 'desc']);

        return view('double-entry::journal_entry.index', compact('journals'));
    }

    /**
     * Show the form for viewing the specified resource.
     *
     * @return Response
     */
    public function show(Journal $journal_entry)
    {
        return view('double-entry::journal_entry.show', compact('journal_entry'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $accounts = [];

        Account::with('type')
            ->enabled()
            ->orderBy('code')
            ->get()
            ->each(function ($account) use (&$accounts) {
                $accounts[trans($account->type->name)][$account->id] = $account->code . ' - ' . $account->trans_name;
            });

        ksort($accounts);

        $currencies = Currency::enabled()->pluck('name', 'code');

        $currency = Currency::code(setting('default.currency'))->first();

        $journal_number = $this->getNextDocumentNumber('double-entry.journal');

        $basis = $this->getBasis();

        $file_type_mimes = explode(',', config('filesystems.mimes'));

        $file_types = [];

        foreach ($file_type_mimes as $mime) {
            $file_types[] = '.' . $mime;
        }

        $file_types = implode(',', $file_types);

        return view('double-entry::journal_entry.create', compact('accounts', 'currency', 'journal_number', 'basis', 'currencies', 'file_types'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     *
     * @return Response
     */
    public function store(Request $request)
    {
        $this->dispatch(new CreateJournalEntry($request));

        $message = trans('messages.success.added', ['type' => trans('double-entry::general.journal_entry')]);

        flash($message)->success();

        return response()->json([
            'success' => true,
            'error' => false,
            'data' => [],
            'redirect' => route('double-entry.journal-entry.index'),
            'message' => $message,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Journal  $journal_entry
     *
     * @return Response
     */
    public function edit(Journal $journal_entry)
    {
        $journal = $journal_entry;

        $accounts = [];

        Account::with('type')
            ->enabled()
            ->orderBy('code')
            ->get()
            ->each(function ($account) use (&$accounts) {
                $accounts[trans($account->type->name)][$account->id] = $account->code . ' - ' . $account->trans_name;
            });

        ksort($accounts);

        foreach ($journal->ledgers as $ledger) {
            if (!empty($ledger->debit)) {
                $journal->debit_account_id = $ledger->account_id;
                $journal->debit_amount = $ledger->debit;
            } else {
                $journal->credit_account_id = $ledger->account_id;
                $journal->credit_amount = $ledger->credit;
            }
        }

        $currencies = Currency::enabled()->pluck('name', 'code');

        $currency = Currency::code($journal->currency_code)->first();

        if (is_null($journal->currency_code)) {
            $currency = Currency::code(setting('default.currency'))->first();

            $journal->currency_code = $currency->code;
            $journal->currency_rate = $currency->rate;
        }

        $basis = $this->getBasis();

        $journal_items = $journal->ledgers()
            ->get()
            ->each(function ($ledger) {
                $ledger->castCredit();
                $ledger->castDebit();
            })
            ->toJson();

        $file_type_mimes = explode(',', config('filesystems.mimes'));

        $file_types = [];

        foreach ($file_type_mimes as $mime) {
            $file_types[] = '.' . $mime;
        }

        $file_types = implode(',', $file_types);

        return view('double-entry::journal_entry.edit', compact('journal', 'accounts', 'currency', 'basis', 'currencies', 'journal_items', 'file_types'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Journal  $journal_entry
     * @param  Request  $request
     *
     * @return Response
     */
    public function update(Journal $journal_entry, Request $request)
    {
        $this->dispatch(new UpdateJournalEntry($journal_entry, $request));

        $message = trans('messages.success.updated', ['type' => trans('double-entry::general.journal_entry')]);

        flash($message)->success();

        return response()->json([
            'success' => true,
            'error' => false,
            'data' => [],
            'redirect' => route('double-entry.journal-entry.index'),
            'message' => $message,
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Journal  $journal_entry
     *
     * @return Response
     */
    public function destroy(Journal $journal_entry)
    {
        $this->dispatch(new DeleteJournalEntry($journal_entry));

        $message = trans('messages.success.deleted', ['type' => trans('double-entry::general.journal_entry')]);

        flash($message)->success();

        return response()->json([
            'success' => true,
            'error' => false,
            'data' => $message,
            'message' => '',
            'redirect' => route('double-entry.journal-entry.index'),
        ]);
    }

    /**
     * Duplicate the specified resource.
     *
     * @param  Journal  $journal_entry
     *
     * @return Response
     */
    public function duplicate(Journal $journal_entry)
    {
        $clone = $journal_entry->duplicate();

        $message = trans('messages.success.duplicated', ['type' => trans('double-entry::general.journal_entry')]);

        flash($message)->success();

        return redirect()->route('double-entry.journal-entry.edit', $clone->id);
    }

    /**
     * Import the specified resource.
     *
     * @param  ImportRequest  $request
     *
     * @return Response
     */
    public function import(ImportRequest $request)
    {
        $response = $this->importExcel(new Import, $request, trans('double-entry::general.journal_entry'));

        if ($response['success']) {
            $response['redirect'] = route('double-entry.journal-entry.index');

            flash($response['message'])->success();
        } else {
            $response['redirect'] = route('import.create', ['double-entry', 'journal-entry']);

            flash($response['message'])->error()->important();
        }

        return response()->json($response);
    }

    /**
     * Export the specified resource.
     *
     * @return Response
     */
    public function export()
    {
        return $this->exportExcel(new Export, trans('double-entry::general.journal_entry'));
    }
}

modules/DoubleEntry/Resources/views/journal_entry/create.blade.php
@extends('layouts.admin')

@section('title', trans('general.title.new', ['type' => trans('double-entry::general.journal_entry')]))

@section('content')
<!-- Default box -->
    <div class="card">
        {!! Form::open([
            'id' => 'journal-entry',
            'route' => ['double-entry.journal-entry.store'],
            'method' => 'POST',
            '@submit.prevent' => 'onSubmit',
            '@keydown' => 'form.errors.clear($event.target.name)',
            'files' => true,
            'role' => 'form',
            'class' => 'form-loading-button',
            'novalidate' => true
        ]) !!}

    <div class="card-body">
        <div class="row">
            {{ Form::dateGroup('paid_at', trans('general.date'), 'calendar', ['id' => 'paid_at', 'class' => 'form-control datepicker', 'required' => 'required', 'show-date-format' => company_date_format(), 'date-format' => 'Y-m-d', 'autocomplete' => 'off'], Date::now()->toDateString()) }}

            {{ Form::textGroup('journal_number', trans_choice('general.numbers', 1), 'file', ['required' => 'required'], $journal_number) }}

            {{ Form::textGroup('reference', trans('general.reference'), 'file-text-o', []) }}

            {{ Form::selectGroup('currency_code', trans_choice('general.currencies', 1), 'exchange-alt', $currencies, $currency->code, ['required' => 'required', 'model' => 'form.currency_code', 'change' => 'onChangeCurrency']) }}
            {!! Form::hidden('currency_rate', $currency->rate, ['id' => 'currency_rate', 'class' => 'form-control', 'required' => 'required']) !!}

            {{ Form::selectGroup('basis', trans('general.basis'), '', $basis) }}

            {{ Form::textareaGroup('description', trans('general.description'), '', '', ['rows' => '3', 'required' => 'required']) }}

            {{ Form::fileGroup('attachment', trans('general.attachment'), '', ['dropzone-class' => 'w-100', 'multiple' => 'multiple', 'options' => ['acceptedFiles' => $file_types]], null, 'col-md-12') }}

            <div class="col-md-12">
                {!! Form::label('items', trans_choice('general.items', 2), ['class' => 'control-label']) !!}
                <div class="table-responsive">
                    <table class="table table-bordered" id="items">
                        <thead class="thead-light">
                            <tr class="row">
                                @stack('actions_th_start')
                                <th class="col-md-1 action-column border-right-0 border-bottom-0" required>{{ trans('general.actions') }}</th>
                                @stack('actions_th_end')
                                @stack('name_th_start')
                                <th class="col-md-3 text-left border-right-0 border-bottom-0">{{ trans('double-entry::general.account') }}</th>
                                @stack('name_th_end')
                                @stack('notes_th_start')
                                <th class="col-md-4 text-left border-right-0 border-bottom-0">{{ trans_choice('general.notes', 1) }}</th>
                                @stack('notes_th_end')
                                @stack('quantity_th_start')
                                <th class="col-md-2 text-left border-right-0 border-bottom-0">{{ trans('double-entry::general.debit') }}</th>
                                @stack('quantity_th_end')
                                @stack('price_th_start')
                                <th class="col-md-2 text-left border-right-1 border-bottom-0">{{ trans('double-entry::general.credit') }}</th>
                                @stack('price_th_end')
                            </tr>
                        </thead>
                        <tbody>

                        @include('double-entry::journal_entry.item')

                        @stack('add_item_td_start')
                        <tr id="addItem">
                            <td class="col-md-1 action-column border-right-1 border-bottom-0"><button type="button" @click="onAddItem" id="button-add-item" data-toggle="tooltip" title="{{ trans('general.add') }}" class="btn btn-icon btn-outline-success btn-lg" data-original-title="{{ trans('general.add') }}"><i class="fa fa-plus"></i></button></td>
                        </tr>
                        @stack('add_item_td_end')

                        @stack('sub_total_td_start')
                        <tr class="row" id="tr-subtotal">
                            <td class="text-right col-md-8">
                                <strong>{{ trans('invoices.sub_total') }}</strong>
                            </td>
                            <td class="text-right col-md-2">
                                {{ Form::moneyGroup('debit_sub', '', '', ['disabled' => true, 'v-model' => 'sub.debit_formatted', 'currency' => $currency, 'dynamic-currency' => 'currency', 'masked' => 'true'], 0.00, 'text-right d-none') }}
                                <span id="debit-sub" v-html="sub.debit_formatted"></span>
                            </td>
                            <td class="text-right col-md-2">
                                {{ Form::moneyGroup('credit_sub', '', '', ['disabled' => true, 'v-model' => 'sub.credit_formatted', 'currency' => $currency, 'dynamic-currency' => 'currency', 'masked' => 'true'], 0.00, 'text-right d-none') }}
                                <span id="credit-sub" v-html="sub.credit_formatted"></span>
                            </td>
                        </tr>
                        @stack('sub_total_td_end')

                        @stack('grand_total_td_start')
                        <tr class="row">
                            <td class="text-right col-md-8"><strong>{{ trans('invoices.total') }}</strong></td>
                            <td class="text-right col-md-2" :style="{ background: color.debit}">
                                {{ Form::moneyGroup('debit_total', '', '', ['disabled' => true, 'v-model' => 'total.debit_formatted', 'currency' => $currency, 'dynamic-currency' => 'currency', 'masked' => 'true'], 0.00, 'text-right d-none') }}
                                <span id="debit-total" v-html="total.debit_formatted"></span>
                            </td>
                            <td class="text-right col-md-2" :style="{ background: color.credit}">
                                {{ Form::moneyGroup('credit_total', '', '', ['disabled' => true, 'v-model' => 'total.credit_formatted', 'currency' => $currency, 'dynamic-currency' => 'currency', 'masked' => 'true'], 0.00, 'text-right d-none') }}
                                <span id="credit-total" v-html="total.credit_formatted"></span>
                            </td>
                        </tr>
                        @stack('grand_total_td_end')
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- /.box-body -->

        <div class="card-footer">
            <div class="row float-right">
                <div class="">
                    <a href="{{ route('double-entry.journal-entry.index') }}" class="btn btn-icon btn-outline-secondary header-button-top">
                        <span class="btn-inner--icon"><i class="fas fa-times"></i></span>
                        <span class="btn-inner--text">{{ trans('general.cancel') }}</span>
                    </a>

                    {!! Form::button(
                    '<div v-if="form.loading" class="aka-loader-frame"><div class="aka-loader"></div></div> <span :class="[{\'opacity-10\': journal_button}]" v-if="!form.loading" class="btn-inner--icon"><i class="fas fa-save"></i></span>' . '<span :class="[{\'opacity-10\': journal_button}]" class="btn-inner--text"> ' . trans('general.save') . '</span>',
                    [':disabled' => 'journal_button || form.loading', 'type' => 'submit', 'class' => 'btn btn-icon btn-success button-submit header-button-top', 'data-loading-text' => trans('general.loading')]) !!}
                </div>
            </div>
        </div>

        <!-- /.box-footer -->
        {{ Form::hidden('currency_code', $currency->code, ['id' => 'currency_code']) }}
        {!! Form::close() !!}
    </div>
@endsection

@push('scripts_start')
    <script src="{{ asset('modules/DoubleEntry/Resources/assets/js/journal-entries.min.js?v=' . module_version('double-entry')) }}"></script>
@endpush

modules/DoubleEntry/Resources/views/journal_entry/index.blade.php
@extends('layouts.admin')

@section('title', trans('double-entry::general.journal_entry'))

@section('new_button')
    @can('create-double-entry-journal-entry')
        <a href="{{ route('double-entry.journal-entry.create') }}" class="btn btn-sm btn-success header-button-top">{{ trans('general.add_new') }}</a>
        <a href="{{ route('import.create', ['double-entry', 'journal-entry']) }}" class="btn btn-white btn-sm">{{ trans('import.import') }}</a>
    @endcan
    <a href="{{ route('double-entry.journal-entry.export', request()->input()) }}" class="btn btn-white btn-sm">{{ trans('general.export') }}</a>
@endsection

@section('content')
    @if ($journals->count() || request()->get('search', false))
        <div class="card">
            <div class="card-header border-bottom-0" :class="[{'bg-gradient-primary': bulk_action.show}]">
                {!! Form::open([
                    'method' => 'GET',
                    'route' => 'double-entry.journal-entry.index',
                    'role' => 'form',
                    'class' => 'mb-0'
                ]) !!}
                    <div class="align-items-center" v-if="!bulk_action.show">
                        <x-search-string model="Modules\DoubleEntry\Models\Journal" />
                    </div>

                    {{ Form::bulkActionRowGroup('double-entry::general.journal_entry', $bulk_actions, ['group' => 'double-entry', 'type' => 'journal-entry']) }}
                {!! Form::close() !!}
            </div>

            <div class="table-responsive">
                <table class="table table-flush table-hover" id="tbl-taxes">
                        <thead class="thead-light">
                            <tr class="row table-head-line">
                                <th class="col-sm-2 col-md-1 col-lg-1 col-xl-1 d-none d-sm-block">{{ Form::bulkActionAllGroup() }}</th>
                                <th class="col-md-2 col-lg-2 col-xl-2 d-none d-md-block">{{ trans_choice('general.numbers', 1) }}</th>
                                <th class="col-xs-3 col-sm-3 col-md-2 col-lg-2 col-xl-2">@sortablelink('paid_at', trans('general.date'))</th>
                                <th class="col-xs-3 col-sm-2 col-md-2 text-right amount-space">@sortablelink('amount', trans('general.amount'))</th>
                                <th class="col-xs-4 col-sm-3 col-md-2 col-lg-2 col-xl-2">{{ trans('general.description') }}</th>
                                <th class="col-md-2 d-none d-md-block">{{ trans('general.reference') }}</th>
                                <th class="col-xs-2 col-sm-2 col-md-1 col-lg-1 col-xl-1 text-center">{{ trans('general.actions') }}</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($journals as $item)
                                <tr class="row align-items-center border-top-1">
                                    <td class="col-sm-2 col-md-1 col-lg-1 col-xl-1 d-none d-sm-block">{{ Form::bulkActionGroup($item->id, 'journal_' . $item->id ) }}</td>
                                    <td class="col-md-2 col-lg-2 col-xl-2 d-none d-md-block"><a href="{{ route('double-entry.journal-entry.show', $item->id) }}">{{ $item->journal_number }}</a></td>
                                    <td class="col-xs-3 col-sm-3 col-md-2 col-lg-2 col-xl-2 border-0">@date($item->paid_at)</td>
                                    <td class="col-xs-3 col-sm-2 col-md-2 text-right amount-space">@money($item->amount, $item->currency_code ?? setting('default.currency'), true)</td>
                                    <td class="col-xs-4 col-sm-3 col-md-2 col-lg-2 col-xl-2 border-0 long-texts">{{ $item->description }}</td>
                                    <td class="col-md-2 d-none d-md-block border-0 long-texts">{{ $item->reference }}</td>
                                    <td class="col-xs-2 col-sm-2 col-md-1 col-lg-1 col-xl-1 text-center">
                                        <div class="dropdown">
                                            <a class="btn btn-neutral btn-sm text-light items-align-center p-2" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                <i class="fa fa-ellipsis-h text-muted"></i>
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                                <a class="dropdown-item" href="{{ route('double-entry.journal-entry.show', $item->id) }}">{{ trans('general.show') }}</a>
                                                @can('update-double-entry-journal-entry')
                                                    <div class="dropdown-divider"></div>    
                                                    <a class="dropdown-item" href="{{ route('double-entry.journal-entry.edit', $item->id) }}">{{ trans('general.edit') }}</a>
                                                @endcan('update-double-entry-journal-entry')
                                                @can('create-double-entry-journal-entry')
                                                    <div class="dropdown-divider"></div>
                                                    <a class="dropdown-item" href="{{ route('double-entry.journal-entry.duplicate', $item->id) }}">{{ trans('general.duplicate') }}</a>
                                                @endcan
                                                @can('delete-double-entry-journal-entry')
                                                    <div class="dropdown-divider"></div>
                                                    {!! Form::deleteLink($item, 'double-entry.journal-entry.destroy', 'double-entry::general.journal_entry') !!}
                                                @endcan
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                </table>
            </div>

            <div class="card-footer table-action">
                <div class="row">
                    @include('partials.admin.pagination', ['items' => $journals])
                </div>
            </div>
        </div>
    @else
        <x-empty-page 
            page="manual-journal" 
            image-empty-page="{{ asset('modules/DoubleEntry/Resources/assets/img/manual-journal.png') }}"
            text-empty-page="double-entry::general.empty.manual_journal"
            text-page="double-entry::general.journal_entry"
            url-docs-path="https://akaunting.com/docs/app-manual/accounting/double-entry"
            permission-create="create-double-entry-journal-entry"
            route-create="double-entry.journal-entry.create"
        />
    @endif
@endsection

@push('scripts_start')
    <script src="{{ asset('modules/DoubleEntry/Resources/assets/js/journal-entries.min.js?v=' . module_version('double-entry')) }}"></script>
@endpush

modules/DoubleEntry/Resources/views/journal_entry/item.blade.php
<tr class="row" v-for="(row, index) in form.items" :index="index">
    @stack('actions_td_start')
        <td class="col-md-1 action-column border-right-0 border-bottom-0">
            @stack('actions_button_start')
            <button type="button"
                @click="onDeleteItem(index)"
                data-toggle="tooltip"
                title="{{ trans('general.delete') }}"
                class="btn btn-icon btn-outline-danger btn-lg"><i class="fa fa-trash"></i>
            </button>
            @stack('actions_button_end')
        </td>
    @stack('actions_td_end')

    @stack('account_id_td_start')
        <td class="col-md-3 border-right-0 border-bottom-0">
            @stack('account_id_input_start')
            <akaunting-select
                class="mb-0 select-tax"
                :form-classes="[{'has-error': form.errors.has('items.' + index + '.account_id') }]"
                :group="true"
                :placeholder="'{{ trans('general.form.select.field', ['field' => trans_choice('general.accounts', 1)]) }}'"
                name="account_id"
                :value="form.items[index].account_id"
                :options="{{ json_encode($accounts) }}"
                @interface="row.account_id = $event"
                :value="row.account_id"
                :multiple="false"
                :collapse="false"
                :form-error="form.errors.get('items.' + index + '.account_id')"
                :no-data-text="'{{ trans('general.no_data') }}'"
                :no-matching-data-text="'{{ trans('general.no_matching_data') }}'"
            ></akaunting-select>
            {!! $errors->first('account_id', '<p class="help-block">:message</p>') !!}
            @stack('account_id_input_end')
        </td>
    @stack('account_td_end')

    @stack('notes_td_start')
        <td class="col-md-4 border-right-0 border-bottom-0">
            @stack('account_id_input_start')
                {{ Form::textGroup('note', '', '', ['v-model' => 'form.items[index].notes', 'placeholder' => trans('general.form.enter', ['field' => trans_choice('general.notes', 1)])], null, 'col-12') }}
            @stack('account_id_input_end')
        </td>
    @stack('notes_td_end')

    @stack('debit_td_start')
        <td class="col-md-2 border-right-0 border-bottom-0">
            @stack('debit_input_start')
            {{ Form::moneyGroup('debit', '', '', ['required' => 'required', 'disabled' => 'row.has_credit', 'v-model' => 'row.debit', 'data-item' => 'debit', 'currency' => $currency, 'dynamic-currency' => 'currency', 'change' => 'row.debit = $event; onCalculateJournal', 'v-error' => "form.errors.get('items.' + index + '.debit')", 'masked' => true], 0.00, 'text-right input-price') }}
            <input value="{{ $currency->code }}"
                name="item.currency"
                data-item="currency"
                v-model="row.currency"
                @input="onCalculateJournal"
                type="hidden">
            {!! $errors->first('item.debit', '<p class="help-block">:message</p>') !!}
            @stack('debit_input_end')
        </td>
    @stack('debit_td_end')

    @stack('credit_td_start')
        <td class="col-md-2 border-right-1 border-bottom-0">
            @stack('credit_input_start')
            {{ Form::moneyGroup('credit', '', '', ['required' => 'required', 'disabled' => 'row.has_debit', 'v-model' => 'row.credit', 'data-item' => 'credit', 'currency' => $currency, 'dynamic-currency' => 'currency', 'change' => 'row.credit = $event; onCalculateJournal', 'v-error' => "form.errors.get('items.' + index + '.credit')", 'masked' => true], 0.00, 'text-right input-price') }}
            <input value="{{ $currency->code }}"
                    name="item.currency"
                    data-item="currency"
                    v-model="row.currency"
                    @input="onCalculateJournal"
                    type="hidden">
        {!! $errors->first('item.credit', '<p class="help-block">:message</p>') !!}
            @stack('credit_input_end')
        </td>
    @stack('credit_td_end')
</tr>

modules/DoubleEntry/Resources/views/journal_entry/show.blade.php
@extends('layouts.admin')

@section('title', trans('double-entry::general.journal_entry'))

@section('new_button')
    <x-transactions.show.top-buttons
        type="journal"
        :transaction="$journal_entry"
        hide-button-group-divider1
        hide-button-email
        hide-button-print
        hide-button-share
        hide-button-pdf
        text-delete-modal="double-entry::general.journal_entry"
    />
@endsection

@section('content')
    <x-transactions.show.content
        type="journal"
        :transaction="$journal_entry"
        hide-header-account
        hide-header-category
        hide-header-contact
        hide-account
        hide-category
        hide-contact
        hide-payment-methods
        hide-footer-histories
        text-header-account=""
        text-description="{{ trans('general.description') }}"
        text-content-title="{{ trans('double-entry::general.journal_entry') }}"
    />
@endsection

@push('scripts_start')
    <link rel="stylesheet" href="{{ asset('public/css/print.css?v=' . version('short')) }}" type="text/css">

    <x-transactions.script type="journal" />
@endpush